sudo: true

language: python

python:
   - "3.6"

dist: trusty

cache: pip

install:
   - pip install tox-travis
   - pip install codecov
   - pip install requirements.txt

script:
   - tox --version
   - tox
   - coverage run runtests.py
   - if [ ${TRAVIS} ]; then  codecov -t "3c3cbcea-c530-438a-af73-ff73c1ede243";  fi